name: OmniScrape
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.10,<3.11.0a0
  - r-base
  - spyder
  - sra-tools >=3.0.0
  - parallel-fastq-dump
  - jupyterlab
  - firefox
  - geoparse
  - cython
